Create Recover Password View and add to router
leuzaoo/app-encontre pull request #18
Opened 2022-07-01 12:17 UTC by leuzaoo

- Foi criada a página de recuperação de senha;
- Foi adicionada ao Router também, porém estava dando algum erro e não consegui entender o motivo do mesmo, então comentei a linha que estava dando o erro para podermos consertar.

2022-07-01 14:50 UTC, thismarcoantonio requested changes

2022-07-01 14:50 UTC, thismarcoantonio commented on src/Pages/RecoverPasswordView.vue
> +  <main-header />
Esse Header está multiplicando nas páginas. O Header principal está sendo inserido no arquivo App.vue

2022-07-01 14:50 UTC, thismarcoantonio commented on src/Pages/RecoverPasswordView.vue
> +      <main-button text>Cancelar</main-button>
Faltou o `router-link` para a página de login

2022-07-01 14:50 UTC, thismarcoantonio commented on src/Pages/RecoverPasswordView.vue
> +      <main-button>Enviar</main-button>
Faltou o type submit

2022-07-01 14:50 UTC, thismarcoantonio commented on src/Pages/RecoverPasswordView.vue
> +const state = reactive({ name: "", lastName: "", email: "", password: "" });
Aqui a gente só tá usando o email.

2022-07-02 02:41 UTC, leuzaoo commented on src/Pages/RecoverPasswordView.vue
> +      <main-button text>Cancelar</main-button>
Essa correção eu não consegui entender.

2022-07-02 02:46 UTC, leuzaoo commented
Confirma pra mim @thismarcoantonio se eu não cometi nenhum erro ao fazer essa PR por favor.

2022-07-02 15:06 UTC, thismarcoantonio requested changes

2022-07-02 15:06 UTC, thismarcoantonio commented on src/Pages/RecoverPasswordView.vue
> +      <main-button text>Cancelar</main-button>
@leuzaoo 

```
<router-link to="/sign-in">
      <main-button text>Cancelar</main-button>
</router-link>
```

2022-07-03 02:36 UTC, thismarcoantonio approved these changes
Fiz alguns ajustes gerais em todas as páginas em relação a cor, espaçamento e etc, mas no geral já estava certo.

2022-07-03 02:36 UTC, merged