Update Profile view
leuzaoo/app-encontre pull request #39
Opened 2022-07-17 14:21 UTC by leuzaoo

- Atualizado os botões;
- Inserido componente de "LocationCard";

2022-07-18 12:50 UTC, leuzaoo commented
@thismarcoantonio foi ajustado a responsividade da página de perfil para desktop.

2022-07-18 14:58 UTC, thismarcoantonio requested changes
O layout no desktop ainda não tá funcionando bem. O conteúdo no centro deveria ter uma largura máxima de `1152px`, mas parece que está muito menor, excluindo o conteúdo do topo e o botão de sair da conta.

![localhost_4000_profile](https://user-images.githubusercontent.com/25869417/179540271-35db64f9-a0f1-4274-af18-914e2a5adfec.png)

2022-07-18 14:58 UTC, thismarcoantonio commented on src/pages/ProfileView.vue
> +    <h3 class="text-4xl mt-16">Perfil</h3>
Você pode ver que a gente tá usando H3 aqui, outro H3 em baixo e um H2 mais pra baixo ainda. Semanticamente isso está incorreto, pois um H2 nunca deve ter menos importância q um H3. Você pode trocar tudo isso por uma `div` ou colocar o "Perfil" como H3 e o resto como H3

2022-07-18 14:58 UTC, thismarcoantonio commented on src/pages/ProfileView.vue
> +  </div>
Talvez seja bom a gente deixar isso como está no figma, pra no futuro ficar mais fácil colocar o conteúdo dentro, mas não é 100% necessário.

2022-07-18 14:58 UTC, thismarcoantonio commented on src/pages/ProfileView.vue
> +        >
Aparentemente aqui não ficou bem formatado, e esse botão por ser o submit deveria estar dentro do `form`.

```suggestion
        <main-button :disabled="!meta.dirty" class="mr-3">
          Atualizar
        </main-button>
```

2022-07-19 22:22 UTC, leuzaoo commented on src/pages/ProfileView.vue
> +        >
Aqui está corrigido (estou adicionando estes comentários para que saibamos o que foi corrigido).

2022-07-19 22:26 UTC, leuzaoo commented on src/pages/ProfileView.vue
> +  </div>
Aqui alterei a cor para branco, e tirei o texto "content".

2022-07-19 22:34 UTC, leuzaoo commented on src/pages/ProfileView.vue
> +    <h3 class="text-4xl mt-16">Perfil</h3>
Foram todos alterados para H3.

2022-07-20 02:29 UTC, merged