Tab header component
leuzaoo/app-encontre pull request #40
Opened 2022-07-18 15:10 UTC by leuzaoo

- Criado componente "TabHeader";
- Adicionado ícones no componente;
- Adicionado as declarativas dos ícones.

2022-07-19 14:21 UTC, thismarcoantonio requested changes
Eu entendi a sua ideia, mas acho que seria mais legal se a gente alterasse alguns pontos para no futuro esse componente ser reutilizável:
- Mudar o nome do componente de `TabHeader` para `CategoryFilters`.
- Receber como prop um array chamado `categories`, onde os objetos dentro do array sejam tipo:
```
{
  id?: string;
  icon: string;
  label: string;
}
```
- Quando clicar na categoria, emitir um evento no estilo `select-category`, jogando a categoria escolhida pra fora (naquele esquema do `defineEmits`).
- Receber uma prop `active` com o id da categoria.

2022-07-19 14:21 UTC, thismarcoantonio commented on src/components/TabHeader.vue
> +    <div class="flex flex-col items-center">
Aqui é uma boa oportunidade pra usar `ul` e `li`

2022-07-19 14:21 UTC, thismarcoantonio commented on src/components/TabHeader.vue
> +  </div>
Acho que isso deveria estar fora desse componente

2022-07-22 13:47 UTC, thismarcoantonio requested changes

2022-07-22 13:47 UTC, thismarcoantonio commented on src/components/CategoryFilters.vue
> +    class="bg-white text-xs gap-6 p-5 rounded-md shadow-sm mb-12 overflow-x-auto"
Aqui nessa div a gente tem o container desse elemento. 
Segundo o figma o container tem `16px` de padding. Também não precisamos do `gap-6` nem `mb-12` (a margem entre outros elementos deve ir sempre fora do componente para facilitar o reuso. 

```suggestion
    class="bg-white text-xs p-4 rounded-md shadow-sm overflow-x-auto"
```

2022-07-22 13:47 UTC, thismarcoantonio commented on src/components/CategoryFilters.vue
> +    <ul class="flex mr-6">
Aqui a margem não está fazendo nada:
```suggestion
    <ul class="flex">
```

2022-07-22 13:47 UTC, thismarcoantonio commented on src/pages/HomeView.vue
> +  <h1>Home</h1>
Acho que não precisamos adicionar esse `<h1>`

2022-07-22 13:55 UTC, leuzaoo commented on src/pages/HomeView.vue
> +  <h1>Home</h1>
Ok

2022-07-22 13:58 UTC, leuzaoo commented on src/components/CategoryFilters.vue
> +    class="bg-white text-xs gap-6 p-5 rounded-md shadow-sm mb-12 overflow-x-auto"
Ok

2022-07-22 13:58 UTC, leuzaoo commented on src/components/CategoryFilters.vue
> +    <ul class="flex mr-6">
Ok

2022-07-22 14:04 UTC, thismarcoantonio approved these changes

2022-07-22 14:04 UTC, merged